# Uncomment this line to define a global platform for your project
platform :ios, "10.0"
use_frameworks!
inhibit_all_warnings!

abstract_target 'App' do

  target 'ProductsApp' do
    pod 'Nuke', '~> 5.2'
  end

  target 'Kit' do
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'Bolts-Swift', '~> 1.3.0'
    pod 'SVProgressHUD', '~> 2.1.2'
    
    target 'KitTests' do
      inherit! :search_paths
      pod 'OHHTTPStubs/Swift', '~> 6.0.0'
      pod 'Quick', '1.1.0'
      pod 'Nimble', '7.0.1'
    end
  end
  
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end

